services:
  redis:
    image: redis:7
    container_name: moviehub-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: moviehub-postgres
    environment:
      POSTGRES_DB: moviehub
      POSTGRES_USER: moviehub_user
      POSTGRES_PASSWORD: moviehub_pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: moviehub-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@moviehub.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin
  #     # - ./pgadmin_config:/pgadmin4/servers.json
  #   restart: unless-stopped

  minio:
    image: minio/minio
    container_name: moviehub-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO web console
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

# volumes:
#   postgres_data:
#   minio_data: