# Generated by Django 6.0.2 on 2026-03-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_actor_genre_movie_delete_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
