# Generated by Django 6.0.2 on 2026-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_movie_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
