# Generated by Django 6.0.2 on 2026-03-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
    ]
