"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# FastEmbed / Hugging Face downloads (project root, not system /tmp or ~/.cache)
FASTEMBED_CACHE_DIR = Path(
    os.environ.get("FASTEMBED_CACHE_DIR", str(BASE_DIR / "huggingface_cache"))
)
FASTEMBED_CACHE_DIR.mkdir(parents=True, exist_ok=True)
# Single cache root for FastEmbed and huggingface_hub (avoid split hub/ + cache_dir races)
os.environ.setdefault("HF_HOME", str(FASTEMBED_CACHE_DIR))
os.environ.setdefault("HUGGINGFACE_HUB_CACHE", str(FASTEMBED_CACHE_DIR))
# Safer downloads when many Celery workers start at once (avoids partial xet blobs)
os.environ.setdefault("HF_HUB_ENABLE_HF_TRANSFER", "0")


def env_bool(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-8yss5j_waxde@qwvvrj3w&b!umn-k+22bdvvgis9f+wj%)3k@p",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "django_extensions",
    "debug_toolbar",
    "django_celery_results",
    'apps.users',
    'apps.content',
    'django_filters',
    'storages',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "moviehub"),
        "USER": os.environ.get("DB_USER", "moviehub_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "moviehub_pass"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = "users.User" # Tells Django to Use Custom User

THROTTLE_RATE_USER = os.environ.get("THROTTLE_RATE_USER", "300/min")
THROTTLE_RATE_ANON = os.environ.get("THROTTLE_RATE_ANON", "120/min")
# Sensitive flows (forgot password) — separate scope, stricter default
THROTTLE_RATE_AUTH = os.environ.get("THROTTLE_RATE_AUTH", "20/min")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": THROTTLE_RATE_USER,
        "anon": THROTTLE_RATE_ANON,
        "auth": THROTTLE_RATE_AUTH,
    },
    "DEFAULT_PAGINATION_CLASS":"rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 7,
    "DEFAULT_FILTER_BACKEND":[
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ]
}

# Local dev: SPA + React Strict Mode easily exceeds 3/min anon. Disable global throttling in DEBUG.
if DEBUG and env_bool("THROTTLE_DISABLE_IN_DEBUG", True):
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # will not send the real mail only console logs.

DOMAIN = os.environ.get("DOMAIN", "http://localhost:8000")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@example.com")

_default_cors = "http://localhost:5173,http://127.0.0.1:5173"
_cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", _default_cors)
_frontend_origins = [
    o.strip() for o in _cors_origins.split(",") if o.strip()
] or [o.strip() for o in _default_cors.split(",")]

CORS_ALLOWED_ORIGINS = _frontend_origins

# Required for POST from the Vite dev server (Origin: http://localhost:5173), including proxied /api calls.
CSRF_TRUSTED_ORIGINS = _frontend_origins

# Dev: allow the Vite app (any port) to call the API directly when not using the proxy.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)

INTERNAL_IPS = ["127.0.0.1", "localhost"]


def _show_debug_toolbar(request):
    if not DEBUG:
        return False
    if request.path.startswith("/api/"):
        return False
    return True


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": "config.settings._show_debug_toolbar",
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1), # Set the desired access token lifetime
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # Set the desired refresh token lifetime
    # ... other settings
}

# Celery
"""
Redis DB 0 → Task queue (broker)
Redis DB 1 → Task results (backend)
"""

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "django-db")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Enables extend task result attributes (name, args, kwargs, worker, ertires, queue, delivery_info)
CELERY_RESULT_EXTENDED = True


# Media upload field
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Use S3 backend (MinIO compatible)
STORAGES = {
    "default": {
        "BACKEND": "config.storage.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "admin")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "password123")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "mybucket")
AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL", "http://localhost:9000")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")
AWS_QUERYSTRING_AUTH = env_bool("AWS_QUERYSTRING_AUTH", False)
AWS_S3_USE_SSL = env_bool("AWS_S3_USE_SSL", False)
AWS_S3_ADDRESSING_STYLE = os.environ.get("AWS_S3_ADDRESSING_STYLE", "path")

TMDB_API_KEY = os.environ.get("TMDB_API_KEY", "")
TMDB_ACCESS_TOKEN = os.environ.get("TMDB_ACCESS_TOKEN", "")
